name: GuardUtils
version: ${version}
main: com.flyerzrule.mc.guardutils.GuardUtils
api-version: ${mcVersion}
description: Plugin for making a guard's experience better 
author: [flyerzrule]
depend: [KillionCommons, LuckPerms, ProtocolLib, PacketWrapper]
commands:
  sword:
    description: Requests that a player drops their sword
    usage: /<command> [username]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  bow:
    description: Requests that a player drops their bow
    usage: /<command> [username]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  cb:
    description: Requests that a player drops their other contraband
    usage: /<command> [username] [contrabandItem]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  kos:
    description: Places a player on KOS for the specified amount of time
    usage: /<command> <5|10|cancel|time> <username>
  guardsb:
    description: Toggles the guard scoreboard
    usage: /<command> [on|off]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  guardsinvistag:
    description: Toggles the guard invis tag
    usage: /<command> [on|off]
    permission: guardutils.admin
    permission-message: You do not have permission to use this command.
  guard:
    description: Start and stop a guard shift
permissions:
  guardutils.guard:
    description: Gives access to all guard GuardUtils commands
    default: false
  guardutils.player:
    description: Gives access to all player GuardUtils commands
    default: true
  guardutils.admin:
    description: Gives access to all admin GuardUtils commands
    default: op
  guardutils.guard.scoreboard:
    description: Gives access to the guard scoreboard
    default: false
