name: GuardUtils
version: ${version}
main: com.flyerzrule.mc.guardutils.GuardUtils
api-version: ${mcVersion}
description: Plugin for making a guard's experience better 
author: [flyerzrule]
depend: [KillionCommons, LuckPerms, ProtocolLib, PacketWrapper, SimpleClans]
commands:
  sword:
    description: Requests that a player drops their sword
    usage: /<command> [username]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  bow:
    description: Requests that a player drops their bow
    usage: /<command> [username]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  cb:
    description: Requests that a player drops their other contraband
    usage: /<command> [username] [contrabandItem]
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  kos:
    description: Places a player on KOS for the specified amount of time
    usage: /<command> <5|10|cancel|time> <username>
  guard:
    description: Open the guard menu
    usage: /<command>
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  guardRegister:
    description: Register a player as a guard
    usage: /<command>
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
  guardResign:
    description: Resign from being a guard
    usage: /<command>
    permission: guardutils.guard
    permission-message: You do not have permission to use this command.
permissions:
  guardutils.guard:
    description: Gives access to all guard GuardUtils commands
    default: false
  guardutils.player:
    description: Gives access to all player GuardUtils commands
    default: true
  guardutils.admin:
    description: Gives access to all admin GuardUtils commands
    default: op
  guardutils.guard.scoreboard:
    description: Gives access to the guard scoreboard
    default: false
  guardutils.canBeGuard:
    description: Gives access to the /guardRegister command
    default: false
